# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myUserAdmin
      MONGO_INITDB_ROOT_PASSWORD: myUserAdmin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: myUserAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: myUserAdmin
      ME_CONFIG_MONGODB_URL: mongodb://myUserAdmin:myUserAdmin@mongo:27017/