version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_api
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URL: "mongodb://your_username:your_password@mongodb:27017"
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password

volumes:
  mongodb_data: